### ISSUE TITLE
Audio samples

### ISSUE THREAD

**Issue by francislata** [Rongjiehuang/Multiband-WaveRNN#1]
Hi there! I was wondering if you got this fully working? If so, can you provide some audio samples?

Thank you!

**Comment by Rongjiehuang** [comment]
hi, yes the 2.0 version(semi-multiband) and 3.0 version(fullband) of Multiband_WaveRNN work. Now you could use it. eg: python preprocess.py --hp_file hparams3.0.py 
Further, I will fix bug in 1.0 version(fully-multiband) in several days and  push the code & audio.

**Comment by francislata** [comment]
@Rongjiehuang Thank you! Can you update this issue with a link to the audio once the merge is complete. Thank you!

**Comment by Rongjiehuang** [comment]
Hi, I have uploaded audio samples in https://rongjiehuang.github.io/Multiband-WaveRNN/
