### ISSUE TITLE
Multiband WaveRNN RTF

### ISSUE THREAD

**Issue by YunhaoYuan** [Rongjiehuang/Multiband-WaveRNN#2]
Great work!
May I ask what the RTF of this multiband wavernn vocoder can achieve? 
Is it possible to do real-time synthesizing on cpu?

Thank you

**Comment by Rongjiehuang** [comment]
Hi, I did not implement batched generation, so this unbatched multiband-WaveRNN generated even slower than batched WaveRNN (RTF 1.29).
The advantage of this Multiband-WaveRNN is fast training (4x WaveRNN), we could train Multiband-WaveRNN using LJspeech within one day.
