### ISSUE TITLE
Constant high-frequency noise issue

### ISSUE THREAD

**Issue by francislata** [Rongjiehuang/Multiband-WaveRNN#4]
Hi @Rongjiehuang  - I was wondering if you've encountered something like this in your experiment with multi-band WaveRNN? I find that when I disable the `.astype(np.int64)` call in [here](https://github.com/Rongjiehuang/Multiband-WaveRNN/blob/master/utils/dataset.py#L78) that it doesn't have this constant noise when I resynthesize the audio.

Let me know your thoughts. Note that I'm using a different dataset than LJSpeech and different feature extraction. Thank you.

<img width="801" alt="Screenshot 2021-06-02 at 23 25 31" src="https://user-images.githubusercontent.com/51974347/120582112-f1723980-c3f9-11eb-818e-ab6694cdbd38.png">

**Comment by Rongjiehuang** [comment]
hi, I haven't encountered this constant noise, but I have heard someone else meet with this in other multiband vocoders (e.g., Multiband Parallel WaveGAN). You said that disable the .astype(np.int64) could solve this problem, I think it has something to do with the computational accuracy of GPU machine.

**Comment by francislata** [comment]
@Rongjiehuang however disabling this type-casting wouldn't work when calculating the cross entropy loss as the target labels need to be integer type.

**Comment by Rongjiehuang** [comment]
yes, the labels should be integer. Have you solved this problem, or int32 could help?

**Comment by francislata** [comment]
Unfortunately, I have not solved it.

**Comment by Rongjiehuang** [comment]
I think there is something to do with the sampling rate. You could download VCTK dataset (24K) and try again with the same hparams in `hparams.py`.

**Comment by francislata** [comment]
@Rongjiehuang If you turn off mu-law, do you get those constant lines?

**Comment by Rongjiehuang** [comment]
hi, do you solve it? I have also encountered this noise. There are three main general approaches for these constant lines: 1. hard training for more steps. 2. add discriminator (work in GAN based waveform generation) 3. after PQMF, the full band waveforms pass through an additional conv layer.
